server:
  port: 80
eureka:
  instance:
    hostname: localhost
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/
spring:
  application:
    name: cloud-order
feign:
  client:
    config:
     default:
        connectTimeout: 12000 #单位毫秒
        readTimeout: 12000 #单位毫秒
