server:
  port: 8001

spring:
  application:
    name: cloud-Payment-server
  datasource:
    url: jdbc:mysql://localhost:3306/user-payment?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.atguigu.com.atguiug.springcloud.entites
eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
#    instance-id: ${spring.application.name}:${random.value}
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka7002.com:7002/eureka/,http://eureka7001.com:7001/eureka/