server:
  port: 8002
eureka:
  instance:
#    instance-id: ${spring.application.name}:${random.value}
    hostname: localhost
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka7002.com:7002/eureka/,http://eureka7001.com:7001/eureka/
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/user-payment?useUnicode=true&characterEncoding=utf-8&useSSL=false
  application:
    name: cloud-Payment-server
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.atguigu.com.atguiug.springcloud.entites