server:
  port: 84
eureka:
  instance:
    hostname: localhost
    appname: Hystrix
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,  http://eureka7002.com:7002/eureka/
feign:
  hystrix:
    enabled: true