server:
  port: 9527
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka7002.com:7002/eureka/,http://eureka7001.com:7001/eureka/
  instance:
    hostname: localhost
spring:
  application:
    name: CloudGetWay
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: payment_routh
#          uri: http://localhost:8001
          uri: lb://CLOUD-PAYMENT-SERVER
          predicates:
            - Path=/CreatePayment/**,/GetPayment/**
#            - Before=2023-12-25T14:33:47.789+08:00
#            - Cookie=username,zzyy
#            - Header= H-Request-Id, \d+
#            - Host=MyTest
#            - Method=Get
            #        - id: payment_routh1
            #          uri: http://localhost:8001
            #          uri: lb://CLOUD-PAYMENT-SERVER
            #          predicates:
            #            - Path=/GetPayment/**
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/vhr?useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: root
    password: 123456
mybatis:
  type-aliases-package: com.atguigu.Entity
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
